version: "3"
   
services:
  database:
    image: postgres
    volumes:
      - ./database/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$PSQL_DB_NAME
      - POSTGRES_USER=$PSQL_USER
      - POSTGRES_PASSWORD=$PSQL_USER_PASSWORD

  image-classifier:
    image: tensorflow/serving
    environment:
      - MODEL_NAME=resnet
    volumes:
      - ./models/resnet/:/models/resnet
    ports:
      - "8502:8501"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/export
      - ./minio/config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=$S3_ACCESS_KEY
      - MINIO_SECRET_KEY=$S3_SECRET_KEY
      
    command: server /export

  # Create bucket. See https://github.com/minio/minio/issues/4769#issuecomment-320223201
  minio-createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 $S3_ACCESS_KEY $S3_SECRET_KEY;
      /usr/bin/mc mb myminio/$S3_BUCKETNAME;
      /usr/bin/mc policy set download myminio/$S3_BUCKETNAME;
      exit 0;
      "

  web:
    build: .
    volumes:
      - ./labels.txt:/app/labels.txt
    ports:
      - "8000:8000"
    depends_on:
      - database
      - image-classifier
      - minio
    env_file: 
      - .env